#!/bin/bash

#composer update
#cp .env.example .env
#php artisan key:generate
php artisan serve --host 0.0.0.0 --port 80
php artisan serve --host 0.0.0.0 --port 9000
php artisan serve --host 0.0.0.0 --port 9001
php artisan serve --host 0.0.0.0 --port 9002
